// <auto-generated />
using System;
using CoachsBox.Coaching.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoachsBox.Coaching.Infrastructure.MySqlMigrations.Migrations
{
    [DbContext(typeof(CoachsBoxContext))]
    [Migration("20200705140630_ChangeOnDeleteAgreedPostingRuleFromRestrictToCascade")]
    partial class ChangeOnDeleteAgreedPostingRuleFromRestrictToCascade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoachsBox.Accounting.AccountEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("StudentAccountId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentAccountId");

                    b.ToTable("AccountEntry");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AccountEntry");
                });

            modelBuilder.Entity("CoachsBox.Accounting.PostingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("PostingRule");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PostingRule");
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.AgreementRegistryEntryModel.AgreementRegistryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgreementId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgreementId");

                    b.HasIndex("GroupId")
                        .IsUnique();

                    b.ToTable("AgreementRegistry");
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.CoachingAccountingEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceAgreementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WhenNoticed")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("WhenOccured")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ServiceAgreementId");

                    b.ToTable("CoachingAccountingEvents");

                    b.HasDiscriminator<string>("Discriminator").HasValue("CoachingAccountingEvent");
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.CoachingServiceAgreementModel.CoachingServiceAgreement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("CoachingServiceAgreements");
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.StudentAccountModel.StudentAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentAccounts");
                });

            modelBuilder.Entity("CoachsBox.Coaching.AttendanceLogModel.AttendanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("AttendanceLogs");
                });

            modelBuilder.Entity("CoachsBox.Coaching.BranchModel.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContactPersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContactPersonId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("CoachsBox.Coaching.CoachModel.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("CoachsBox.Coaching.GroupModel.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("CoachsBox.Coaching.PersonModel.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("CoachsBox.Coaching.ScheduleModel.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CoachId");

                    b.HasIndex("GroupId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("CoachsBox.Coaching.StudentModel.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.StudentAccountEntryModel.StudentAccountEntry", b =>
                {
                    b.HasBaseType("CoachsBox.Accounting.AccountEntry");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.HasIndex("GroupId");

                    b.HasDiscriminator().HasValue("StudentAccountEntry");
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.StudentAccountPostingRuleModel.StudentAccountPostingRule", b =>
                {
                    b.HasBaseType("CoachsBox.Accounting.PostingRule");

                    b.HasDiscriminator().HasValue("StudentAccountPostingRule");
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.MonthlyAccrualAccountingEvent", b =>
                {
                    b.HasBaseType("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.CoachingAccountingEvent");

                    b.Property<byte>("TrainingsQuantity")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("MonthlyAccrualAccountingEvent");
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.PaymentAccountingEvent", b =>
                {
                    b.HasBaseType("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.CoachingAccountingEvent");

                    b.HasDiscriminator().HasValue("PaymentAccountingEvent");
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.PersonalTrainingAccrualAccountingEvent", b =>
                {
                    b.HasBaseType("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.CoachingAccountingEvent");

                    b.HasDiscriminator().HasValue("PersonalTrainingAccrualAccountingEvent");
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.StudentAccountPostingRuleModel.MonthlyAccrualPostingRule", b =>
                {
                    b.HasBaseType("CoachsBox.Coaching.Accounting.StudentAccountPostingRuleModel.StudentAccountPostingRule");

                    b.HasDiscriminator().HasValue("MonthlyAccrualPostingRule");
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.StudentAccountPostingRuleModel.PaymentPostingRule", b =>
                {
                    b.HasBaseType("CoachsBox.Coaching.Accounting.StudentAccountPostingRuleModel.StudentAccountPostingRule");

                    b.HasDiscriminator().HasValue("PaymentPostingRule");
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.StudentAccountPostingRuleModel.PersonalTrainingAccrualPostingRule", b =>
                {
                    b.HasBaseType("CoachsBox.Coaching.Accounting.StudentAccountPostingRuleModel.StudentAccountPostingRule");

                    b.HasDiscriminator().HasValue("PersonalTrainingAccrualPostingRule");
                });

            modelBuilder.Entity("CoachsBox.Accounting.AccountEntry", b =>
                {
                    b.HasOne("CoachsBox.Coaching.Accounting.StudentAccountModel.StudentAccount", null)
                        .WithMany("Entries")
                        .HasForeignKey("StudentAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("CoachsBox.Core.Primitives.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("AccountEntryId")
                                .HasColumnType("int");

                            b1.Property<int>("Currency")
                                .HasColumnType("int");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("decimal(65,30)");

                            b1.HasKey("AccountEntryId");

                            b1.ToTable("AccountEntry");

                            b1.WithOwner()
                                .HasForeignKey("AccountEntryId");
                        });
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.AgreementRegistryEntryModel.AgreementRegistryEntry", b =>
                {
                    b.HasOne("CoachsBox.Coaching.Accounting.CoachingServiceAgreementModel.CoachingServiceAgreement", "Agreement")
                        .WithMany()
                        .HasForeignKey("AgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoachsBox.Coaching.GroupModel.Group", null)
                        .WithOne()
                        .HasForeignKey("CoachsBox.Coaching.Accounting.AgreementRegistryEntryModel.AgreementRegistryEntry", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.CoachingAccountingEvent", b =>
                {
                    b.HasOne("CoachsBox.Coaching.Accounting.StudentAccountModel.StudentAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoachsBox.Coaching.GroupModel.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoachsBox.Coaching.Accounting.CoachingServiceAgreementModel.CoachingServiceAgreement", "ServiceAgreement")
                        .WithMany()
                        .HasForeignKey("ServiceAgreementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.AccountingEventProcessingState", "ProcessingState", b1 =>
                        {
                            b1.Property<int>("AccountingEventId")
                                .HasColumnType("int");

                            b1.Property<bool>("IsProcessed")
                                .IsConcurrencyToken()
                                .HasColumnType("tinyint(1)");

                            b1.Property<DateTime>("WhenProcessed")
                                .IsConcurrencyToken()
                                .HasColumnType("datetime(6)");

                            b1.HasKey("AccountingEventId");

                            b1.ToTable("AccountingEventProcessLog");

                            b1.WithOwner("AccountingEvent")
                                .HasForeignKey("AccountingEventId");

                            b1.OwnsMany("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.AccountingEventResultingEntry", "ResultingEntries", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    b2.Property<int>("AccountEntryId")
                                        .HasColumnType("int");

                                    b2.Property<int>("ProcessingStateId")
                                        .HasColumnType("int");

                                    b2.HasKey("Id");

                                    b2.HasIndex("AccountEntryId")
                                        .IsUnique();

                                    b2.HasIndex("ProcessingStateId");

                                    b2.ToTable("AccountingEventResultingEntry");

                                    b2.HasOne("CoachsBox.Accounting.AccountEntry", "AccountEntry")
                                        .WithOne()
                                        .HasForeignKey("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.AccountingEventResultingEntry", "AccountEntryId")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("ProcessingStateId");
                                });
                        });

                    b.OwnsOne("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.CoachingAccountingEventType", "EventType", b1 =>
                        {
                            b1.Property<int>("CoachingAccountingEventId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("CoachingAccountingEventId");

                            b1.ToTable("CoachingAccountingEvents");

                            b1.WithOwner()
                                .HasForeignKey("CoachingAccountingEventId");
                        });
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.CoachingServiceAgreementModel.CoachingServiceAgreement", b =>
                {
                    b.OwnsOne("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.CoachingAccountingEventType", "AccrualEventType", b1 =>
                        {
                            b1.Property<int>("CoachingServiceAgreementId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("CoachingServiceAgreementId");

                            b1.ToTable("CoachingServiceAgreements");

                            b1.WithOwner()
                                .HasForeignKey("CoachingServiceAgreementId");
                        });

                    b.OwnsMany("CoachsBox.Coaching.Accounting.CoachingServiceAgreementModel.AgreedPostingRule", "PostingRules", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("CoachingServiceAgreementId")
                                .HasColumnType("int");

                            b1.Property<int>("PostingRuleId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("CoachingServiceAgreementId");

                            b1.HasIndex("PostingRuleId");

                            b1.ToTable("AgreedPostingRule");

                            b1.WithOwner()
                                .HasForeignKey("CoachingServiceAgreementId");

                            b1.HasOne("CoachsBox.Accounting.PostingRule", "PostingRule")
                                .WithMany()
                                .HasForeignKey("PostingRuleId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.OwnsOne("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.CoachingAccountingEventType", "EventType", b2 =>
                                {
                                    b2.Property<int>("AgreedPostingRuleId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Name")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.HasKey("AgreedPostingRuleId");

                                    b2.ToTable("AgreedPostingRule");

                                    b2.WithOwner()
                                        .HasForeignKey("AgreedPostingRuleId");
                                });
                        });

                    b.OwnsOne("CoachsBox.Core.Primitives.Money", "Rate", b1 =>
                        {
                            b1.Property<int>("CoachingServiceAgreementId")
                                .HasColumnType("int");

                            b1.Property<int>("Currency")
                                .HasColumnType("int");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("decimal(65,30)");

                            b1.HasKey("CoachingServiceAgreementId");

                            b1.ToTable("CoachingServiceAgreements");

                            b1.WithOwner()
                                .HasForeignKey("CoachingServiceAgreementId");
                        });
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.StudentAccountModel.StudentAccount", b =>
                {
                    b.HasOne("CoachsBox.Coaching.StudentModel.Student", null)
                        .WithOne()
                        .HasForeignKey("CoachsBox.Coaching.Accounting.StudentAccountModel.StudentAccount", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoachsBox.Coaching.AttendanceLogModel.AttendanceLog", b =>
                {
                    b.HasOne("CoachsBox.Coaching.GroupModel.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("CoachsBox.Coaching.AttendanceLogModel.AttendanceLogEntry", "Entries", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("AttendanceLogId")
                                .HasColumnType("int");

                            b1.Property<string>("Description")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<bool>("IsTrialTraining")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(false);

                            b1.Property<int>("StudentId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("AttendanceLogId");

                            b1.HasIndex("StudentId");

                            b1.ToTable("AttendanceLogEntry");

                            b1.WithOwner()
                                .HasForeignKey("AttendanceLogId");

                            b1.HasOne("CoachsBox.Coaching.StudentModel.Student", "Student")
                                .WithMany()
                                .HasForeignKey("StudentId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.OwnsOne("CoachsBox.Coaching.AttendanceLogModel.Absence", "AbsenceReason", b2 =>
                                {
                                    b2.Property<int>("AttendanceLogEntryId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Reason")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.HasKey("AttendanceLogEntryId");

                                    b2.ToTable("AttendanceLogEntry");

                                    b2.WithOwner()
                                        .HasForeignKey("AttendanceLogEntryId");
                                });

                            b1.OwnsOne("CoachsBox.Core.Primitives.Date", "Date", b2 =>
                                {
                                    b2.Property<int>("AttendanceLogEntryId")
                                        .HasColumnType("int");

                                    b2.Property<byte>("Day")
                                        .HasColumnType("tinyint unsigned");

                                    b2.Property<int>("Year")
                                        .HasColumnType("int");

                                    b2.HasKey("AttendanceLogEntryId");

                                    b2.ToTable("AttendanceLogEntry");

                                    b2.WithOwner()
                                        .HasForeignKey("AttendanceLogEntryId");

                                    b2.OwnsOne("CoachsBox.Core.Primitives.Month", "Month", b3 =>
                                        {
                                            b3.Property<int>("DateAttendanceLogEntryId1")
                                                .HasColumnType("int");

                                            b3.Property<string>("Name")
                                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                                            b3.Property<int>("Number")
                                                .HasColumnType("int");

                                            b3.HasKey("DateAttendanceLogEntryId1");

                                            b3.ToTable("AttendanceLogEntry");

                                            b3.WithOwner()
                                                .HasForeignKey("DateAttendanceLogEntryId1");
                                        });
                                });

                            b1.OwnsOne("CoachsBox.Core.Primitives.TimeOfDay", "End", b2 =>
                                {
                                    b2.Property<int>("AttendanceLogEntryId")
                                        .HasColumnType("int");

                                    b2.Property<byte>("Hours")
                                        .HasColumnType("tinyint unsigned");

                                    b2.Property<byte>("Minutes")
                                        .HasColumnType("tinyint unsigned");

                                    b2.HasKey("AttendanceLogEntryId");

                                    b2.ToTable("AttendanceLogEntry");

                                    b2.WithOwner()
                                        .HasForeignKey("AttendanceLogEntryId");
                                });

                            b1.OwnsOne("CoachsBox.Core.Primitives.TimeOfDay", "Start", b2 =>
                                {
                                    b2.Property<int>("AttendanceLogEntryId")
                                        .HasColumnType("int");

                                    b2.Property<byte>("Hours")
                                        .HasColumnType("tinyint unsigned");

                                    b2.Property<byte>("Minutes")
                                        .HasColumnType("tinyint unsigned");

                                    b2.HasKey("AttendanceLogEntryId");

                                    b2.ToTable("AttendanceLogEntry");

                                    b2.WithOwner()
                                        .HasForeignKey("AttendanceLogEntryId");
                                });
                        });
                });

            modelBuilder.Entity("CoachsBox.Coaching.BranchModel.Branch", b =>
                {
                    b.HasOne("CoachsBox.Coaching.PersonModel.Person", "ContactPerson")
                        .WithMany()
                        .HasForeignKey("ContactPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("CoachsBox.Coaching.BranchModel.CoachingStaffMember", "CoachingStaff", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<int>("CoachId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("BranchId");

                            b1.HasIndex("CoachId")
                                .IsUnique();

                            b1.ToTable("CoachingStaffMember");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");

                            b1.HasOne("CoachsBox.Coaching.CoachModel.Coach", "Coach")
                                .WithOne()
                                .HasForeignKey("CoachsBox.Coaching.BranchModel.CoachingStaffMember", "CoachId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.OwnsOne("CoachsBox.Core.Primitives.Address", "Address", b1 =>
                        {
                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("Country")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("State")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("Street")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("ZipCode")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("BranchId");

                            b1.ToTable("Branches");

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });
                });

            modelBuilder.Entity("CoachsBox.Coaching.CoachModel.Coach", b =>
                {
                    b.HasOne("CoachsBox.Coaching.PersonModel.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoachsBox.Coaching.GroupModel.Group", b =>
                {
                    b.HasOne("CoachsBox.Coaching.BranchModel.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("CoachsBox.Coaching.GroupModel.EnrolledStudent", "EnrolledStudents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("GroupId")
                                .HasColumnType("int");

                            b1.Property<int>("StudentId")
                                .HasColumnType("int");

                            b1.Property<byte>("TrialTrainingCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint unsigned")
                                .HasDefaultValue((byte)0);

                            b1.Property<DateTime>("WhenEnrolled")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("Id");

                            b1.HasIndex("GroupId");

                            b1.HasIndex("StudentId");

                            b1.ToTable("EnrolledStudent");

                            b1.WithOwner()
                                .HasForeignKey("GroupId");

                            b1.HasOne("CoachsBox.Coaching.StudentModel.Student", "Student")
                                .WithMany()
                                .HasForeignKey("StudentId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.OwnsOne("CoachsBox.Coaching.GroupModel.Sport", "Sport", b1 =>
                        {
                            b1.Property<int>("GroupId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("GroupId");

                            b1.ToTable("Groups");

                            b1.WithOwner()
                                .HasForeignKey("GroupId");
                        });

                    b.OwnsOne("CoachsBox.Coaching.GroupModel.TrainingProgramSpecification", "TrainingProgramm", b1 =>
                        {
                            b1.Property<int>("GroupId")
                                .HasColumnType("int");

                            b1.Property<int>("MaximumAge")
                                .HasColumnType("int");

                            b1.Property<int>("MinimumAge")
                                .HasColumnType("int");

                            b1.HasKey("GroupId");

                            b1.ToTable("Groups");

                            b1.WithOwner()
                                .HasForeignKey("GroupId");
                        });
                });

            modelBuilder.Entity("CoachsBox.Coaching.PersonModel.Person", b =>
                {
                    b.OwnsOne("CoachsBox.Coaching.PersonModel.Gender", "Gender", b1 =>
                        {
                            b1.Property<int>("PersonId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("CoachsBox.Coaching.PersonModel.PersonName", "Name", b1 =>
                        {
                            b1.Property<int>("PersonId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("Patronymic")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<string>("Surname")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.OwnsOne("CoachsBox.Coaching.PersonModel.PersonalInformation", "PersonalInformation", b1 =>
                        {
                            b1.Property<int>("PersonId")
                                .HasColumnType("int");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");

                            b1.OwnsOne("CoachsBox.Coaching.PersonModel.EmailAddress", "Email", b2 =>
                                {
                                    b2.Property<int>("PersonalInformationPersonId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Value")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.HasKey("PersonalInformationPersonId");

                                    b2.ToTable("Persons");

                                    b2.WithOwner()
                                        .HasForeignKey("PersonalInformationPersonId");
                                });

                            b1.OwnsOne("CoachsBox.Coaching.PersonModel.PhoneNumber", "PhoneNumber", b2 =>
                                {
                                    b2.Property<int>("PersonalInformationPersonId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Value")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.HasKey("PersonalInformationPersonId");

                                    b2.ToTable("Persons");

                                    b2.WithOwner()
                                        .HasForeignKey("PersonalInformationPersonId");
                                });

                            b1.OwnsOne("CoachsBox.Core.Primitives.Address", "Address", b2 =>
                                {
                                    b2.Property<int>("PersonalInformationPersonId")
                                        .HasColumnType("int");

                                    b2.Property<string>("City")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.Property<string>("Country")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.Property<string>("State")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.Property<string>("Street")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.Property<string>("ZipCode")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.HasKey("PersonalInformationPersonId");

                                    b2.ToTable("Persons");

                                    b2.WithOwner()
                                        .HasForeignKey("PersonalInformationPersonId");
                                });
                        });

                    b.OwnsOne("CoachsBox.Core.Primitives.Date", "Birthday", b1 =>
                        {
                            b1.Property<int>("PersonId")
                                .HasColumnType("int");

                            b1.Property<byte>("Day")
                                .HasColumnType("tinyint unsigned");

                            b1.Property<int>("Year")
                                .HasColumnType("int");

                            b1.HasKey("PersonId");

                            b1.ToTable("Persons");

                            b1.WithOwner()
                                .HasForeignKey("PersonId");

                            b1.OwnsOne("CoachsBox.Core.Primitives.Month", "Month", b2 =>
                                {
                                    b2.Property<int>("DatePersonId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Name")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.Property<int>("Number")
                                        .HasColumnType("int");

                                    b2.HasKey("DatePersonId");

                                    b2.ToTable("Persons");

                                    b2.WithOwner()
                                        .HasForeignKey("DatePersonId");
                                });
                        });
                });

            modelBuilder.Entity("CoachsBox.Coaching.ScheduleModel.Schedule", b =>
                {
                    b.HasOne("CoachsBox.Coaching.BranchModel.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoachsBox.Coaching.CoachModel.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoachsBox.Coaching.GroupModel.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CoachsBox.Coaching.ScheduleModel.TrainingLocation", "TrainingLocation", b1 =>
                        {
                            b1.Property<int>("ScheduleId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("ScheduleId");

                            b1.ToTable("Schedules");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");

                            b1.OwnsOne("CoachsBox.Core.Primitives.Address", "Address", b2 =>
                                {
                                    b2.Property<int>("TrainingLocationScheduleId")
                                        .HasColumnType("int");

                                    b2.Property<string>("City")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.Property<string>("Country")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.Property<string>("State")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.Property<string>("Street")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.Property<string>("ZipCode")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.HasKey("TrainingLocationScheduleId");

                                    b2.ToTable("Schedules");

                                    b2.WithOwner()
                                        .HasForeignKey("TrainingLocationScheduleId");
                                });
                        });

                    b.OwnsMany("CoachsBox.Coaching.ScheduleModel.TrainingTime", "TrainingList", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("DayOfWeek")
                                .HasColumnType("int");

                            b1.Property<int>("ScheduleId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ScheduleId");

                            b1.ToTable("TrainingTime");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");

                            b1.OwnsOne("CoachsBox.Core.Primitives.Date", "Date", b2 =>
                                {
                                    b2.Property<int>("TrainingTimeId")
                                        .HasColumnType("int");

                                    b2.Property<byte>("Day")
                                        .HasColumnType("tinyint unsigned");

                                    b2.Property<int>("Year")
                                        .HasColumnType("int");

                                    b2.HasKey("TrainingTimeId");

                                    b2.ToTable("TrainingTime");

                                    b2.WithOwner()
                                        .HasForeignKey("TrainingTimeId");

                                    b2.OwnsOne("CoachsBox.Core.Primitives.Month", "Month", b3 =>
                                        {
                                            b3.Property<int>("DateTrainingTimeId")
                                                .HasColumnType("int");

                                            b3.Property<string>("Name")
                                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                                            b3.Property<int>("Number")
                                                .HasColumnType("int");

                                            b3.HasKey("DateTrainingTimeId");

                                            b3.ToTable("TrainingTime");

                                            b3.WithOwner()
                                                .HasForeignKey("DateTrainingTimeId");
                                        });
                                });

                            b1.OwnsOne("CoachsBox.Core.Primitives.TimeOfDay", "End", b2 =>
                                {
                                    b2.Property<int>("TrainingTimeId")
                                        .HasColumnType("int");

                                    b2.Property<byte>("Hours")
                                        .HasColumnType("tinyint unsigned");

                                    b2.Property<byte>("Minutes")
                                        .HasColumnType("tinyint unsigned");

                                    b2.HasKey("TrainingTimeId");

                                    b2.ToTable("TrainingTime");

                                    b2.WithOwner()
                                        .HasForeignKey("TrainingTimeId");
                                });

                            b1.OwnsOne("CoachsBox.Core.Primitives.TimeOfDay", "Start", b2 =>
                                {
                                    b2.Property<int>("TrainingTimeId")
                                        .HasColumnType("int");

                                    b2.Property<byte>("Hours")
                                        .HasColumnType("tinyint unsigned");

                                    b2.Property<byte>("Minutes")
                                        .HasColumnType("tinyint unsigned");

                                    b2.HasKey("TrainingTimeId");

                                    b2.ToTable("TrainingTime");

                                    b2.WithOwner()
                                        .HasForeignKey("TrainingTimeId");
                                });
                        });
                });

            modelBuilder.Entity("CoachsBox.Coaching.StudentModel.Student", b =>
                {
                    b.HasOne("CoachsBox.Coaching.PersonModel.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("CoachsBox.Coaching.StudentModel.Relative", "Relatives", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            b1.Property<int>("PersonId")
                                .HasColumnType("int");

                            b1.Property<int>("StudentId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("PersonId");

                            b1.HasIndex("StudentId");

                            b1.ToTable("Relative");

                            b1.HasOne("CoachsBox.Coaching.PersonModel.Person", "Person")
                                .WithMany()
                                .HasForeignKey("PersonId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("StudentId");

                            b1.OwnsOne("CoachsBox.Coaching.StudentModel.Relationship", "Relationship", b2 =>
                                {
                                    b2.Property<int>("RelativeId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Name")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.HasKey("RelativeId");

                                    b2.ToTable("Relative");

                                    b2.WithOwner()
                                        .HasForeignKey("RelativeId");
                                });
                        });
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.StudentAccountEntryModel.StudentAccountEntry", b =>
                {
                    b.HasOne("CoachsBox.Coaching.GroupModel.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CoachsBox.Coaching.Accounting.StudentAccountEntryModel.StudentAccountEntryType", "EntryType", b1 =>
                        {
                            b1.Property<int>("StudentAccountEntryId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("StudentAccountEntryId");

                            b1.ToTable("AccountEntry");

                            b1.WithOwner()
                                .HasForeignKey("StudentAccountEntryId");
                        });
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.StudentAccountPostingRuleModel.StudentAccountPostingRule", b =>
                {
                    b.OwnsOne("CoachsBox.Coaching.Accounting.StudentAccountEntryModel.StudentAccountEntryType", "EntryType", b1 =>
                        {
                            b1.Property<int>("StudentAccountPostingRuleId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.HasKey("StudentAccountPostingRuleId");

                            b1.ToTable("PostingRule");

                            b1.WithOwner()
                                .HasForeignKey("StudentAccountPostingRuleId");
                        });
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.MonthlyAccrualAccountingEvent", b =>
                {
                    b.OwnsOne("CoachsBox.Core.Primitives.Month", "Month", b1 =>
                        {
                            b1.Property<int>("MonthlyAccrualAccountingEventId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .HasColumnType("longtext CHARACTER SET utf8mb4");

                            b1.Property<int>("Number")
                                .HasColumnType("int");

                            b1.HasKey("MonthlyAccrualAccountingEventId");

                            b1.ToTable("CoachingAccountingEvents");

                            b1.WithOwner()
                                .HasForeignKey("MonthlyAccrualAccountingEventId");
                        });
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.PaymentAccountingEvent", b =>
                {
                    b.OwnsOne("CoachsBox.Core.Primitives.Money", "Amount", b1 =>
                        {
                            b1.Property<int>("PaymentAccountingEventId")
                                .HasColumnType("int");

                            b1.Property<int>("Currency")
                                .HasColumnType("int");

                            b1.Property<decimal>("Quantity")
                                .HasColumnType("decimal(65,30)");

                            b1.HasKey("PaymentAccountingEventId");

                            b1.ToTable("CoachingAccountingEvents");

                            b1.WithOwner()
                                .HasForeignKey("PaymentAccountingEventId");
                        });
                });

            modelBuilder.Entity("CoachsBox.Coaching.Accounting.CoachingAccountingEventModel.PersonalTrainingAccrualAccountingEvent", b =>
                {
                    b.OwnsOne("CoachsBox.Core.Primitives.Date", "TrainingDate", b1 =>
                        {
                            b1.Property<int>("PersonalTrainingAccrualAccountingEventId")
                                .HasColumnType("int");

                            b1.Property<byte>("Day")
                                .HasColumnType("tinyint unsigned");

                            b1.Property<int>("Year")
                                .HasColumnType("int");

                            b1.HasKey("PersonalTrainingAccrualAccountingEventId");

                            b1.ToTable("CoachingAccountingEvents");

                            b1.WithOwner()
                                .HasForeignKey("PersonalTrainingAccrualAccountingEventId");

                            b1.OwnsOne("CoachsBox.Core.Primitives.Month", "Month", b2 =>
                                {
                                    b2.Property<int?>("DatePersonalTrainingAccrualAccountingEventId")
                                        .HasColumnType("int");

                                    b2.Property<string>("Name")
                                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                                    b2.Property<int>("Number")
                                        .HasColumnType("int");

                                    b2.HasKey("DatePersonalTrainingAccrualAccountingEventId");

                                    b2.ToTable("CoachingAccountingEvents");

                                    b2.WithOwner()
                                        .HasForeignKey("DatePersonalTrainingAccrualAccountingEventId");
                                });
                        });

                    b.OwnsOne("CoachsBox.Core.Primitives.TimeOfDay", "EndOfTraining", b1 =>
                        {
                            b1.Property<int>("PersonalTrainingAccrualAccountingEventId")
                                .HasColumnType("int");

                            b1.Property<byte>("Hours")
                                .HasColumnType("tinyint unsigned");

                            b1.Property<byte>("Minutes")
                                .HasColumnType("tinyint unsigned");

                            b1.HasKey("PersonalTrainingAccrualAccountingEventId");

                            b1.ToTable("CoachingAccountingEvents");

                            b1.WithOwner()
                                .HasForeignKey("PersonalTrainingAccrualAccountingEventId");
                        });

                    b.OwnsOne("CoachsBox.Core.Primitives.TimeOfDay", "StartOfTraining", b1 =>
                        {
                            b1.Property<int>("PersonalTrainingAccrualAccountingEventId")
                                .HasColumnType("int");

                            b1.Property<byte>("Hours")
                                .HasColumnType("tinyint unsigned");

                            b1.Property<byte>("Minutes")
                                .HasColumnType("tinyint unsigned");

                            b1.HasKey("PersonalTrainingAccrualAccountingEventId");

                            b1.ToTable("CoachingAccountingEvents");

                            b1.WithOwner()
                                .HasForeignKey("PersonalTrainingAccrualAccountingEventId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
